version: "3"
services:
  dbpostgresqlorder:
    container_name: dbpostgresqlorder
    image: "postgres"
    expose:
      - "5433"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/dbpostgresqlorder/data
    networks:
      - project-network
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  order-service:
    build: order-service
    image: order_service
    container_name: order-service
    platform: linux/amd64
    ports:
      - "8081:8080"
    depends_on:
      - dbpostgresqlorder
    networks:
      - project-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresqlorder:5432/testdb #da lasciare 5432 o da cambiare nel config del db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  spring-cloud-gateway-service:
    build: ./spring-cloud-gateway
    image: ares-gateway
    ports:
      - "9500:9500"
    depends_on:
      - order-service
    environment:
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://order-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: order-id
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/orders/*
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=1
    networks:
      - project-network

volumes:
  db-data:
networks:
  project-network:
    driver: bridge
