version: '3'

services:
  dbpostgresql:
    container_name: postgres2
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appbootrestnet2
    environment:
      POSTGRES_DB: testdb2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  order_app:
    build: .
    image: order_service
    container_name: order_service_stand
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    networks:
      - appbootrestnet2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/testdb2
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  db-data:
networks:
  appbootrestnet2:
    driver: bridge
# docker-compose build && docker-compose up

